import { Order } from '@/db/order';
import { OrderItem } from '@/db/orderItem';

export const MOCK_ORDERS = [
  {
    id: 'order-1',
    code: 'WM-48291',
    customerName: 'Amanda Johnson',
    createdAt: new Date('2026-08-05T18:42:00'),
    status: 'PENDING',
    notes:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer in cursus libero. Aenean id posuere tellus. Nam eu ex porta, hendrerit turpis a, ornare nibh. Proin et placerat turpis. Mauris quam sem, aliquet eget posuere et, posuere sit amet lectus. Nam vitae semper diam. Suspendisse ac sem cursus, fermentum nibh eu, consectetur orci.',
    items: [
      { id: 'item-1', name: 'Cheeseburger', quantity: 2, price: 5.98 },
      { id: 'item-2', name: 'Fries', quantity: 1, price: 5.98 },
      { id: 'item-3', name: 'Cola', quantity: 2, price: 5.98 },
    ] as OrderItem[],
    deliveryFee: 3.5,
    total: 32,
  },
  {
    id: 'order-2',
    code: 'WM-48290',
    customerName: 'Marcus Lee',
    createdAt: new Date('2026-08-05T18:34:00'),
    status: 'ACCEPTED',
    items: [
      { id: 'item-4', name: 'Chicken Wrap', quantity: 1, price: 5.98 },
      { id: 'item-5', name: 'Onion Rings', quantity: 1, price: 5.98 },
    ] as OrderItem[],
    deliveryFee: 3.5,
    total: 21.5,
  },
  {
    id: 'order-3',
    code: 'WM-48289',
    customerName: 'Sofia Martinez',
    createdAt: new Date('2026-08-05T18:21:00'),
    status: 'PREPARING',
    notes: 'No onions',
    items: [
      { id: 'item-6', name: 'Veggie Burger', quantity: 1, price: 5.98 },
      { id: 'item-7', name: 'Sweet Potato Fries', quantity: 1, price: 5.98 },
      { id: 'item-8', name: 'Iced Tea', quantity: 1, price: 5.98 },
    ] as OrderItem[],
    deliveryFee: 3.5,
    total: 25.5,
  },
  {
    id: 'order-4',
    code: 'WM-48288',
    customerName: 'Ethan Williams',
    createdAt: new Date('2026-08-05T18:05:00'),
    status: 'READY',
    items: [
      { id: 'item-9', name: 'Margherita Pizza', quantity: 1, price: 5.98 },
      { id: 'item-10', name: 'Garlic Bread', quantity: 2, price: 5.98 },
    ] as OrderItem[],
    deliveryFee: 3.5,
    total: 27.5,
  },
  {
    id: 'order-5',
    code: 'WM-48287',
    customerName: 'Olivia Brown',
    createdAt: new Date('2026-08-05T17:42:00'),
    status: 'DELIVERED',
    items: [
      { id: 'item-11', name: 'Pepperoni Pizza', quantity: 1, price: 5.98 },
      { id: 'item-12', name: 'Cola', quantity: 2, price: 5.98 },
    ] as OrderItem[],
    deliveryFee: 3.5,
    total: 26.5,
  },
  {
    id: 'order-6',
    code: 'WM-48286',
    customerName: 'Noah Davis',
    createdAt: new Date('2026-08-05T17:18:00'),
    status: 'DELIVERED',
    items: [
      { id: 'item-13', name: 'Caesar Salad', quantity: 1, price: 5.98 },
      { id: 'item-14', name: 'Chicken Wrap', quantity: 1, price: 5.98 },
    ] as OrderItem[],
    deliveryFee: 3.5,
    total: 23.5,
  },
  {
    id: 'order-7',
    code: 'WM-48285',
    customerName: 'Mia Wilson',
    createdAt: new Date('2026-08-05T16:56:00'),
    status: 'CANCELLED',
    notes: 'Well done',
    items: [
      { id: 'item-15', name: 'Cheeseburger', quantity: 1, price: 5.98 },
      { id: 'item-16', name: 'Fries', quantity: 1, price: 5.98 },
    ] as OrderItem[],
    deliveryFee: 3.5,
    total: 19,
  },
  {
    id: 'order-8',
    code: 'WM-48284',
    customerName: 'Lucas Taylor',
    createdAt: new Date('2026-08-05T16:31:00'),
    status: 'DELIVERED',
    items: [
      { id: 'item-17', name: 'Margherita Pizza', quantity: 1, price: 5.98 },
      { id: 'item-18', name: 'Chocolate Cake', quantity: 1, price: 5.98 },
    ] as OrderItem[],
    deliveryFee: 3.5,
    total: 24.5,
  },
  {
    id: 'order-9',
    code: 'WM-48283',
    customerName: 'Emma Anderson',
    createdAt: new Date('2026-08-05T16:04:00'),
    status: 'CANCELLED',
    notes: 'Extra sauce on the side',
    items: [
      { id: 'item-19', name: 'Veggie Burger', quantity: 1, price: 5.98 },
      { id: 'item-20', name: 'Iced Tea', quantity: 1, price: 5.98 },
    ] as OrderItem[],
    deliveryFee: 3.5,
    total: 18.5,
  },
] as Order[];
