export const TEXT = {
  languageCountryISO: 'en-US',
  currency: '$',
  menuTitle: 'Menu',
  menuSubtitle: 'Fresh food made to order',
  all: 'All',
  add: 'Add',
  addedToCart: 'added to cart',
  browseMoreItems: 'Browse more items',
  emptyCart: 'Your cart is empty',
  emptyCartSubtitle: 'Add some items from the menu to get started.',
  browseMenu: 'Browse menu',
  yourCart: 'Your cart',
  clearCart: 'Clear cart',
  deliveryFee: 'Delivery Fee',
  subtotal: 'Subtotal',
  total: 'Total',
  checkout: 'Checkout',
  checkoutSubtitle: 'Confirm your information before placing the order.',
  name: 'Name',
  yourName: 'Your name',
  phone: 'Phone',
  yourPhoneNumber: 'Your phone number',
  notes: 'Notes',
  extraInstructions: 'Extra instructions',
  address: 'Address',
  addressAddLabel: 'include street, number, and neighbourhood',
  yourAddress: 'Your address',
  paymentMethod: 'Payment Method',
  cash: 'Cash',
  card: 'Card',
  changeFor: 'Need change for?',
  startingMoney: '0.00',
  orderSummary: 'Order summary',
  editCart: 'Edit cart',
  placeOrder: 'Place order',
};

export const ERROR_MESSAGES: Record<string, string> = {
  required: 'is required',
  invalid_field: 'is invalid',
  invalid_type: 'is invalid',
  invalid_value: 'is invalid',
  invalid_format: 'has invalid format',
  too_big: 'is too large',
  too_small: 'is too small',
  invalid_payment_method: 'must be "Cash" or "Card"',
  change_for_smaller_than_total: 'must be greater than the order total',
  empty_order: 'Order cannot be empty',
};
