export const TEXT = {
  menuTitle: 'Menu',
  menuSubtitle: 'Fresh food made to order',
  add: 'Add',
  addedToCart: 'added to cart',
  browseMoreItems: 'Browse more items',
  emptyCart: 'Your cart is empty',
  emptyCartSubtitle: 'Add some items from the menu to get started.',
  browseMenu: 'Browse menu',
  yourCart: 'Your cart',
  clearCart: 'Clear cart',
  total: 'Total',
  checkout: 'Checkout',
  checkoutSubtitle: 'Confirm your information before placing the order.',
  name: 'Name',
  yourName: 'Your name',
  phone: 'Phone',
  yourPhoneNumber: 'Your phone number',
  notes: 'Notes',
  extraInstructions: 'Extra instructions',
  orderSummary: 'Order summary',
  editCart: 'Edit cart',
  placeOrder: 'Place order',
};
