export enum ErrorCode {
  REQUIRED,
  INVALID_FIELD,
  INVALID_TYPE,
  INVALID_VALUE,
  INVALID_FORMAT,
  TOO_BIG,
  TOO_SMALL,
  EMPTY_ORDER,
  INVALID_PAYMENT_METHOD,
  CHANGE_FOR_BIGGER_THAN_TOTAL,
}
