export enum ErrorCode {
  REQUIRED = 'required',
  INVALID_FIELD = 'invalid_field',
  INVALID_TYPE = 'invalid_type',
  INVALID_VALUE = 'invalid_value',
  INVALID_FORMAT = 'invalid_format',
  TOO_BIG = 'too_big',
  TOO_SMALL = 'too_small',
  EMPTY_ORDER = 'empty_order',
  INVALID_PAYMENT_METHOD = 'invalid_payment_method',
  CHANGE_FOR_SMALLER_THAN_TOTAL = 'change_for_smaller_than_total',
  ORDER_NOT_FOUND = 'order_not_found',
  WEAK_PASSWORD = 'weak_password',
  ALREADY_REGISTERED = 'already_registered',
  ALREADY_IN_USE = 'already_in_use',
  WRONG_CREDENTIALS = 'wrong_credentials',
  ITEM_NOT_DELETED = 'item_not_deleted',
  STATUS_NOT_UPDATED = 'status_not_updated',
  FAILED_TO_OPEN_CLOSE_RESTAURANT = 'failed_to_open_close_restaurant',
  FAILED_TO_UPDATE_RESTAURANT = 'failed_to_update_restaurant',
  RESTAURANT_CLOSED = 'restaurant_closed',
  UNAVAILABLE_ITEMS = 'unavailable_items',
}
